export * from "./course.entity";
export * from "./index";
export * from "./pensum.entity";
export * from "./period.entity";
export * from "./representant.entity";
export * from "./roles.entity";
export * from "./student.entity";
export * from "./teacher.entity";
export * from "./user.entity";
